name: spatio-temporal-extremes
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - abseil-cpp=20211102.0
  - aiofiles=22.1.0
  - aiosqlite=0.18.0
  - anyio=3.5.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arrow-cpp=11.0.0
  - asciitree=0.3.3
  - asttokens=2.0.5
  - attrs=22.1.0
  - aws-c-common=0.6.8
  - aws-c-event-stream=0.1.6
  - aws-checksums=0.1.11
  - aws-sdk-cpp=1.8.185
  - babel=2.11.0
  - backcall=0.2.0
  - beautifulsoup4=4.12.2
  - black=23.3.0
  - blas=1.0
  - bleach=4.1.0
  - bokeh=3.2.1
  - boost-cpp=1.82.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.08.22
  - cartopy=0.21.1
  - certifi=2023.7.22
  - cffi=1.15.1
  - cftime=1.6.2
  - charset-normalizer=2.0.4
  - click=8.0.4
  - cloudpickle=2.2.1
  - cmcrameri=1.7
  - colorama=0.4.6
  - comm=0.1.2
  - contourpy=1.0.5
  - cryptography=41.0.3
  - cuda-cccl=12.1.109
  - cuda-cudart=11.8.89
  - cuda-cudart-dev=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-libraries-dev=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvrtc-dev=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-profiler-api=12.2.140
  - cuda-runtime=11.8.0
  - cycler=0.11.0
  - cytoolz=0.12.0
  - dask=2023.6.0
  - dask-core=2023.6.0
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - distributed=2023.6.0
  - entrypoints=0.4
  - executing=0.8.3
  - fasteners=0.16.3
  - filelock=3.9.0
  - fonttools=4.25.0
  - freetype=2.12.1
  - geos=3.8.0
  - gflags=2.2.2
  - giflib=5.2.1
  - glib=2.69.1
  - glog=0.5.0
  - grpc-cpp=1.48.2
  - hdf4=4.2.13
  - hdf5=1.12.1
  - heapdict=1.0.1
  - icc_rt=2022.1.0
  - icu=58.2
  - idna=3.4
  - importlib-metadata=6.0.0
  - intel-openmp=2023.1.0
  - ipykernel=6.25.0
  - ipython=8.15.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.0.4
  - jedi=0.18.1
  - jinja2=3.1.2
  - joblib=1.2.0
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.17.3
  - jupyter=1.0.0
  - jupyter_client=7.4.9
  - jupyter_console=6.6.3
  - jupyter_core=5.3.0
  - jupyter_events=0.6.3
  - jupyter_server=1.23.4
  - jupyter_server_fileid=0.9.0
  - jupyter_server_ydoc=0.8.0
  - jupyter_ydoc=0.2.4
  - jupyterlab=3.6.3
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.22.0
  - jupyterlab_widgets=3.0.5
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lerc=3.0
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcublas=11.11.3.6
  - libcublas-dev=11.11.3.6
  - libcufft=10.9.0.58
  - libcufft-dev=10.9.0.58
  - libcurand=10.3.2.106
  - libcurand-dev=10.3.2.106
  - libcurl=8.1.1
  - libcusolver=11.4.1.48
  - libcusolver-dev=11.4.1.48
  - libcusparse=11.7.5.86
  - libcusparse-dev=11.7.5.86
  - libdeflate=1.17
  - libevent=2.1.12
  - libffi=3.4.4
  - libiconv=1.16
  - libjpeg-turbo=2.0.0
  - libnetcdf=4.8.1
  - libnpp=11.8.0.86
  - libnpp-dev=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libnvjpeg-dev=11.9.0.86
  - libpng=1.6.39
  - libpq=12.15
  - libprotobuf=3.20.3
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libthrift=0.15.0
  - libtiff=4.5.1
  - libuv=1.44.2
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxml2=2.10.4
  - libxslt=1.1.37
  - libzip=1.8.0
  - locket=1.0.0
  - lxml=4.9.3
  - lz4=4.3.2
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - matplotlib=3.7.2
  - matplotlib-base=3.7.2
  - matplotlib-inline=0.1.6
  - mistune=0.8.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpmath=1.3.0
  - msgpack-python=1.0.3
  - munkres=1.1.4
  - mypy_extensions=1.0.0
  - nbclassic=0.5.5
  - nbclient=0.5.13
  - nbconvert=6.5.4
  - nbformat=5.9.2
  - nest-asyncio=1.5.6
  - netcdf4=1.6.2
  - networkx=3.1
  - ninja=1.10.2
  - ninja-base=1.10.2
  - notebook=6.5.4
  - notebook-shim=0.2.2
  - numcodecs=0.11.0
  - numexpr=2.8.4
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openssl=3.0.11
  - orc=1.7.4
  - packaging=23.1
  - pandocfilters=1.5.0
  - parso=0.8.3
  - partd=1.4.0
  - pathspec=0.10.3
  - pcre=8.45
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.2.1
  - platformdirs=3.10.0
  - ply=3.11
  - proj=8.2.1
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.36
  - prompt_toolkit=3.0.36
  - psutil=5.9.0
  - pure_eval=0.2.2
  - pyarrow=11.0.0
  - pycparser=2.21
  - pygments=2.15.1
  - pyopenssl=23.2.0
  - pyparsing=3.0.9
  - pyproj=3.4.1
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrsistent=0.18.0
  - pyshp=2.1.3
  - pysocks=1.7.1
  - python=3.11.5
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-json-logger=2.0.7
  - python-lmdb=1.4.1
  - python-tzdata=2023.3
  - pytorch=2.1.0
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pywin32=305
  - pywinpty=2.0.10
  - pyyaml=6.0
  - pyzmq=23.2.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtconsole=5.4.2
  - qtpy=2.2.0
  - qtwebkit=5.212
  - re2=2022.04.01
  - requests=2.31.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - scikit-learn=1.3.0
  - send2trash=1.8.0
  - setuptools=68.0.0
  - shapely=2.0.1
  - sip=6.6.2
  - six=1.16.0
  - snappy=1.1.9
  - sniffio=1.2.0
  - sortedcontainers=2.4.0
  - soupsieve=2.4
  - sqlite=3.41.2
  - stack_data=0.2.0
  - sympy=1.11.1
  - tbb=2021.8.0
  - tblib=1.7.0
  - terminado=0.17.1
  - threadpoolctl=2.2.0
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - toolz=0.12.0
  - tornado=6.3.2
  - traitlets=5.7.1
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - tzdata=2023c
  - urllib3=1.26.16
  - utf8proc=2.6.1
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.38.4
  - widgetsnbextension=4.0.5
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - xarray=2023.6.0
  - xyzservices=2022.9.0
  - xz=5.4.2
  - y-py=0.5.9
  - yaml=0.2.5
  - ypy-websocket=0.8.2
  - zarr=2.13.3
  - zeromq=4.3.4
  - zict=3.0.0
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
    - autopep8==2.0.2
    - configobj==5.0.8
    - dc-stat-think==1.1.1
    - einops==0.6.1
    - fsspec==2023.5.0
    - huggingface-hub==0.14.1
    - isodisreg==0.1
    - isort==5.12.0
    - llvmlite==0.40.1
    - numba==0.57.1
    - osqp==0.6.3
    - pandas==2.0.1
    - properscoring==0.1
    - pybind11==2.11.1
    - pycodestyle==2.11.0
    - pykdtree==1.3.9
    - pyreadr==0.4.7
    - pyresample==1.27.1
    - pytz==2023.3
    - qdldl==0.1.7.post0
    - safetensors==0.3.1
    - scipy==1.10.1
    - seaborn==0.12.2
    - timm==0.9.2
    - torchaudio==2.1.0
    - torchvision==0.16.0
    - tqdm==4.65.0
